version: '3'

services:
  control-center-rtsp:
    build: ./rtsp
    image: "control-center-rtsp"
    ports:
      - "60554:60554"
    tty: true
    networks:
        default_bridge:
          ipv4_address: 172.36.0.2

  control-center-web:
    build: ./web
    image: "control-center-web"
    ports:
      - "60080:5000"
    tty: true
    depends_on:
      - "control-center-rtsp"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  
    networks:
        default_bridge:
          ipv4_address: 172.36.0.3

  attacker-ubuntu:
    build: ./attacker
    image: "attacker-ubuntu"
    ports:
      - "6080:80"
      - "5900:5900"
    environment:
      - VNC_PASSWORD=yamang
    volumes:
      - /dev/shm:/dev/shm
    networks:
        default_bridge:
          ipv4_address: 172.36.0.100

  # attacker-kali:
  #   build: ./attacker
  #   image: "attacker-kali"
  #   ports:
  #    - "25900:5900"
  #    - "25901:5901"
  #   tty: true
  #   networks:
  #       default_bridge:
  #         ipv4_address: 172.36.0.100
          
networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.36.0.0/24